-- Jeremy Zhou, jzhou83
-- Miles Lee, mlee276

DROP TABLE IF EXISTS Company;
DROP TABLE IF EXISTS MarketIndex;
DROP TABLE IF EXISTS Bond;
DROP TABLE IF EXISTS SectorETF;
DROP TABLE IF EXISTS OptionVolume;