<head><title> Q15 </title></head>
<body>

<?php
include 'open.php';

//Override the PHP configuration file to display all errors
//This is useful during development but generally disabled before release
ini_set('error_reporting', E_ALL);
ini_set('display_errors', true);

//Collect the posted value in a variable called $ticker
$indexTicker = $_POST['indexTicker'];
$bondTicker = $_POST['bondTicker'];

echo "<h2>Q15: List the months where the ".$bondTicker." bond outperformed the ".$indexTicker." index.</h2>";

$dataPoints = array();

//Determine if any input was actually collected
if (empty($indexTicker) or empty($bondTicker)) {

   echo "Empty inputs detected.<br><br>";

}

else {

   if ($stmt = $conn->prepare("CALL Q15(?, ?)")) {
      $stmt->bind_param("ss", $indexTicker, $bondTicker);

      //Run the actual query
      if ($stmt->execute()) {

         //Store result set generated by the prepared statement
         $result = $stmt->get_result();

         if ($result->num_rows == 0) {
            //Result contains no rows at all
            echo "Invalid dates, Invalid tickers, or no data from those dates.";
         } else {
	 
            //Create table to display results
            echo "<table border=\"1px solid black\">";
            echo "<tr><th> Month </th><th> Year </th></tr>";

            //Report result set by visiting each row in it
            while ($row = $result->fetch_row()) {
               echo "<tr>";
               echo "<td>".$row[0]."</td>";
               echo "<td>".$row[1]."</td>";
               echo "</tr>";
            } 
            echo "</table>";
         }	 

         //We are done with the result set returned above, so free it
         $result->free_result();
      
      } else {

         //Call to execute failed, e.g. because server is no longer reachable,
	 //or because supplied values are of the wrong type
         echo "Execute failed.<br>";
      }

      //Close down the prepared statement
      $stmt->close();

   } else {

       //A problem occurred when preparing the statement; check for syntax errors
       //and misspelled attribute names in the statement string.
      echo "Prepare failed.<br>";
      $error = $conn->errno . ' ' . $conn->error;
      echo $error; 
   }


}

//Close the connection created in open.php
$conn->close();
?>


