<head><title> Q6 </title></head>
<body>

<?php
include 'open.php';

//Override the PHP configuration file to display all errors
//This is useful during development but generally disabled before release
ini_set('error_reporting', E_ALL);
ini_set('display_errors', true);

//Collect the posted value in a variable called $ticker
$indexTicker = $_POST['indexTicker'];
$bondTicker = $_POST['bondTicker'];
$weekDateStart = $_POST['weekDateStart'];
$weekDateEnd = $_POST['weekDateEnd'];

echo "<h2>Q6: Of what weeks between ".$weekDateStart." and ".$weekDateEnd." dates were the ".$bondTicker." bond red and the ".$indexTicker." index green?</h2>";

$dataPoints = array();

//Determine if any input was actually collected
if (empty($indexTicker) or empty($bondTicker) or empty($weekDateStart) or empty($weekDateEnd)) {

   echo "Empty inputs detected.<br><br>";

}

else {

   if ($stmt = $conn->prepare("CALL Q6(?, ?, ?, ?)")) {
      $stmt->bind_param("ssss", $indexTicker, $bondTicker, $weekDateStart, $weekDateEnd);

      //Run the actual query
      if ($stmt->execute()) {

         //Store result set generated by the prepared statement
         $result = $stmt->get_result();

         if ($weekDateStart > $weekDateEnd) {
            echo "Error: Start date is after end date.";
         } elseif ($weekDateStart < '2011-04-05' || $weekDateEnd > '2021-04-05') {
            echo "Invalid dates.";
         } elseif ($result->num_rows == 0) {
            //Result contains no rows at all
            echo "Invalid dates, invalid tickers, or no result from those dates.";
         } else {
	 
            //Create table to display results
            echo "<table border=\"1px solid black\">";
            echo "<tr><th> Monday Dates of the Weeks </th></tr>";

            //Report result set by visiting each row in it
            while ($row = $result->fetch_row()) {
               echo "<tr>";
               echo "<td>".$row[1]."</td>";
               echo "</tr>";
            } 
            echo "</table>";
         }	 

         //We are done with the result set returned above, so free it
         $result->free_result();
      
      } else {

         //Call to execute failed, e.g. because server is no longer reachable,
	 //or because supplied values are of the wrong type
         echo "Execute failed.<br>";
      }

      //Close down the prepared statement
      $stmt->close();

   } else {

       //A problem occurred when preparing the statement; check for syntax errors
       //and misspelled attribute names in the statement string.
      echo "Prepare failed.<br>";
      $error = $conn->errno . ' ' . $conn->error;
      echo $error; 
   }


}

//Close the connection created in open.php
$conn->close();
?>


